### ISSUE TITLE
question on permissions

### ISSUE THREAD

**Issue by IzzySoft** [apk-editor/APK-Explorer-Editor#73]
My scanner got a few additional checks in January, and on today's update reported:

```
! repo/com.apk.editor_28.apk declares sensitive permission(s):
  android.permission.REQUEST_INSTALL_PACKAGES android.permission.QUERY_ALL_PACKAGES
  android.permission.READ_PHONE_STATE android.permission.READ_EXTERNAL_STORAGE
! repo/com.apk.editor_28.apk contains signature block blobs: 0x504b4453 (DEPENDENCY_INFO_BLOCK; GOOGLE)
```

I was able to align most of the above permissions:

```yaml
    android.permission.REQUEST_INSTALL_PACKAGES: needed for the APK/Bundle installer component 
    android.permission.QUERY_ALL_PACKAGES: needed to list the apps to explore
    android.permission.READ_EXTERNAL_STORAGE: needed to explore the storage for APK files
    android.permission.WRITE_EXTERNAL_STORAGE: needed to save/export files
```

Just `READ_PHONE_STATE` escaped me. Can you please clarify what that's needed for?

Oh, that `DEPENDENCY_INFO_BLOCK` can easily be avoided:

```gradle
android {
    dependenciesInfo {
        // Disables dependency metadata when building APKs.
        includeInApk = false
        // Disables dependency metadata when building Android App Bundles.
        includeInBundle = false
    }
}
```

For some background: that BLOB is supposed to be just a binary representation of your app's dependency tree. But as it's encrypted with a public key belonging to Google, only Google can read it – and nobody else can even verify what it really contains.

Thanks in advance!
